### ISSUE TITLE
Missing label for io.buildpacks.builder.metadata

### ISSUE THREAD

**Issue by macalinao** [paketo-buildpacks/poetry#207]
## Expected Behavior
Should allow pack build

## Current Behavior
```
ERROR: failed to build: invalid builder gcr.io/paketo-buildpacks/poetry: builder gcr.io/paketo-buildpacks/poetry:latest missing label io.buildpacks.builder.metadata -- try recreating builder
```

## Possible Solution
Add the label to the build

## Steps to Reproduce

Run
```
pack build --builder=gcr.io/paketo-buildpacks/poetry <anything>
```

```
$ pack --version                                                                                         
0.29.0
```

## Motivations
I can't build my Poetry project

**Comment by robdimsdale** [comment]
@macalinao the issue here is that `poetry` is a _buildpack_, not a builder. You could use `poetry` as part of the python buildpack, which is included in the `base` builder. So your command would look like:

```
pack build --builder=paketobuildpacks/builder-jammy-base <anything>
```

I'm going to close this issue because I think the above command should work. If it doesn't work for you, please feel free to re-open.
